steps:
- name: 'gcr.io/cloud-builders/docker'
  timeout: 86400s
  args: [ 'build', '-t', 'gcr.io/qwiklabs-gcp-04-c896ba6f194d/dockerfile', '.' ]
  timeout: 86400s
timeout: 86400s

options:
  pool:
    name: 'projects/qwiklabs-gcp-04-c896ba6f194d/locations/southamerica-east1/workerPools/I3'
    
